### ISSUE TITLE
Documentation Requires Uninitialized Constant

### ISSUE THREAD

**Issue by CodingAnarchy** [nepalez/dry-initializer-rails#1]
`extend Dry::Initializer::Rails` only results in a `uninitialized constant Dry::Initializer::Rails (NameError)`, yet this is what is indicated as necessary in the official documentation for `dry-initializer`.

This documentation appears to need correction.

**Comment by stgeneral** [comment]
Was already fixed in a81a8b3a1deeb9d36bd77d97f7c573988d825112.
