### ISSUE TITLE
how about use a find_or_create_by option

### ISSUE THREAD

**Issue by ranska** [nepalez/dry-initializer-rails#3]
Hello,
I saw there is the option to use 

```
find_by: :name
```
In some case it can be good to have some default model like default value for string or int
```
find_or_create_by: :name
```
Is it hard to implement ?

**Comment by stgeneral** [comment]
I don’t think this is change will be for good. 

The idea of initializer just to initialize but not perform any business logic. Especially such heavy like inserting into database.

**Comment by ranska** [comment]
Thanks for this quick reply.

Ok I understand you point.
So in term of design what type of style/pattern would you use when find_by_return nothing ?
What is for you the best practice ?

**Comment by stgeneral** [comment]
@ranska it depends on the context and what would you like to achieve. 

If you are building a kind of a Command or Service object, just write that line `find_or_create_by` manually, e.g.:

```ruby
class UserCreateCommand
  # include dry-initializer-rails
  param :name

  def perform
    @user = User.find_or_create_by(name: name)
    # ...
  end
end
```

By the way, you can check out our gem https://github.com/ergoserv/auxiliary_rails#command-objects, where we've implemented a kind of **Command pattern** using dry-initializer and dry-initializer-rails.
